# Funding links shown on the repository's "Sponsor" button.
# See https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [jwh3times]
buy_me_a_coffee: jwh3times
