// <auto-generated />
using System;
using LeaseBook.Web.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeaseBook.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721020013_M8_AddImportBatchSupersedesBatchId")]
    partial class M8_AddImportBatchSupersedesBatchId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeaseBook.Modules.Accounting.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BankAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_account_id");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("class");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("OrgId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_org_id_code");

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_accounts_bank_account_id_matches_class", "(bank_account_id IS NOT NULL) = (class IN ('trust_bank','pm_operating_bank'))");

                            t.HasCheckConstraint("ck_accounts_class", "class IN ('trust_bank','owner_equity','tenant_receivable','deposit_liability','pm_income','pm_operating_bank','migration_clearing')");
                        });
                });

            modelBuilder.Entity("LeaseBook.Modules.Accounting.Domain.AccountingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_accounting_periods");

                    b.HasIndex("OrgId", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("ix_accounting_periods_org_id_year_month");

                    b.ToTable("accounting_periods", null, t =>
                        {
                            t.HasCheckConstraint("ck_accounting_periods_month", "month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("ck_accounting_periods_status", "status IN ('open','closed')");
                        });
                });

            modelBuilder.Entity("LeaseBook.Modules.Accounting.Domain.BankLineState", b =>
                {
                    b.Property<Guid>("JournalLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_line_id");

                    b.Property<DateTime?>("ClearedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cleared_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid?>("ReconciliationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reconciliation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("JournalLineId")
                        .HasName("pk_bank_line_status");

                    b.HasIndex("ReconciliationId")
                        .HasDatabaseName("ix_bank_line_status_reconciliation_id");

                    b.HasIndex("OrgId", "Status")
                        .HasDatabaseName("ix_bank_line_status_org_id_status");

                    b.ToTable("bank_line_status", null, t =>
                        {
                            t.HasCheckConstraint("ck_bank_line_status_status", "status IN ('uncleared','cleared','reconciled')");
                        });
                });

            modelBuilder.Entity("LeaseBook.Modules.Accounting.Domain.BankReconciliation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<Guid?>("FinalizedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("finalized_by");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<int>("PeriodMonth")
                        .HasColumnType("integer")
                        .HasColumnName("period_month");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("integer")
                        .HasColumnName("period_year");

                    b.Property<string>("ReopenReason")
                        .HasColumnType("text")
                        .HasColumnName("reopen_reason");

                    b.Property<string>("ReportSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("report_snapshot");

                    b.Property<decimal>("StatementEndingBalance")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("statement_ending_balance");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_bank_reconciliations");

                    b.HasIndex("OrgId", "BankAccountId", "PeriodYear", "PeriodMonth")
                        .IsUnique()
                        .HasDatabaseName("ix_bank_reconciliations_org_id_bank_account_id_period_year_per");

                    b.ToTable("bank_reconciliations", null, t =>
                        {
                            t.HasCheckConstraint("ck_bank_reconciliations_status", "status IN ('in_progress','finalized','reopened')");
                        });
                });

            modelBuilder.Entity("LeaseBook.Modules.Accounting.Domain.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("EventSubtype")
                        .HasColumnType("text")
                        .HasColumnName("event_subtype");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<Guid?>("ReversesEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_entry_id");

                    b.Property<string>("SourceRef")
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("ReversesEntryId")
                        .HasDatabaseName("ix_journal_entries_reverses_entry_id");

                    b.HasIndex("OrgId", "EntryDate")
                        .HasDatabaseName("ix_journal_entries_org_id_entry_date");

                    b.HasIndex("OrgId", "ReversesEntryId")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entries_org_id_reverses_entry_id")
                        .HasFilter("reverses_entry_id IS NOT NULL");

                    b.HasIndex("OrgId", "SourceRef")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entries_org_id_source_ref")
                        .HasFilter("source_ref IS NOT NULL");

                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("LeaseBook.Modules.Accounting.Domain.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_class");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("BankAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_account_id");

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("basis");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Credit")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("credit");

                    b.Property<decimal?>("Debit")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("debit");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<string>("Memo")
                        .HasColumnType("text")
                        .HasColumnName("memo");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_journal_lines");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_journal_lines_account_id");

                    b.HasIndex("EntryId")
                        .HasDatabaseName("ix_journal_lines_entry_id");

                    b.HasIndex("OrgId", "AccountId")
                        .HasDatabaseName("ix_journal_lines_org_id_account_id");

                    b.HasIndex("OrgId", "BankAccountId")
                        .HasDatabaseName("ix_journal_lines_org_id_bank_account_id");

                    b.HasIndex("OrgId", "EntryId")
                        .HasDatabaseName("ix_journal_lines_org_id_entry_id");

                    b.HasIndex("OrgId", "OwnerId")
                        .HasDatabaseName("ix_journal_lines_org_id_owner_id");

                    b.HasIndex("OrgId", "TenantId")
                        .HasDatabaseName("ix_journal_lines_org_id_tenant_id");

                    b.ToTable("journal_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_journal_lines_account_class", "account_class IN ('trust_bank','owner_equity','tenant_receivable','deposit_liability','pm_income','pm_operating_bank','migration_clearing')");

                            t.HasCheckConstraint("ck_journal_lines_basis", "basis IN ('cash','accrual','both')");

                            t.HasCheckConstraint("ck_journal_lines_debit_xor_credit", "(debit IS NULL) <> (credit IS NULL) AND COALESCE(debit, credit) > 0");

                            t.HasCheckConstraint("ck_journal_lines_pm_income_no_owner", "account_class <> 'pm_income' OR owner_id IS NULL");
                        });
                });

            modelBuilder.Entity("LeaseBook.Modules.Banking.Domain.BankCsvMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_account_id");

                    b.Property<string>("ColumnMapJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("column_map_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.HasKey("Id")
                        .HasName("pk_bank_csv_mappings");

                    b.HasIndex("OrgId", "BankAccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_bank_csv_mappings_org_id_bank_account_id_name");

                    b.ToTable("bank_csv_mappings", (string)null);
                });

            modelBuilder.Entity("LeaseBook.Modules.Banking.Domain.StatementImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_account_id");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<Guid?>("ImportedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("imported_by");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_statement_imports");

                    b.HasIndex("OrgId", "BankAccountId")
                        .HasDatabaseName("ix_statement_imports_org_id_bank_account_id");

                    b.ToTable("statement_imports", (string)null);
                });

            modelBuilder.Entity("LeaseBook.Modules.Banking.Domain.StatementLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dedup_hash");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("ImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_id");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateOnly>("StatementDate")
                        .HasColumnType("date")
                        .HasColumnName("statement_date");

                    b.HasKey("Id")
                        .HasName("pk_statement_lines");

                    b.HasIndex("ImportId")
                        .HasDatabaseName("ix_statement_lines_import_id");

                    b.HasIndex("OrgId", "BankAccountId", "DedupHash")
                        .IsUnique()
                        .HasDatabaseName("ix_statement_lines_org_id_bank_account_id_dedup_hash");

                    b.ToTable("statement_lines", (string)null);
                });

            modelBuilder.Entity("LeaseBook.Modules.Banking.Domain.StatementMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<Guid?>("JournalLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_line_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid>("StatementLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("statement_line_id");

                    b.HasKey("Id")
                        .HasName("pk_statement_matches");

                    b.HasIndex("StatementLineId")
                        .HasDatabaseName("ix_statement_matches_statement_line_id");

                    b.ToTable("statement_matches", null, t =>
                        {
                            t.HasCheckConstraint("ck_statement_matches_kind", "kind IN ('matched','suggested','unmatched','created')");
                        });
                });

            modelBuilder.Entity("LeaseBook.Modules.Directory.Domain.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Institution")
                        .HasColumnType("text")
                        .HasColumnName("institution");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Mask")
                        .HasColumnType("text")
                        .HasColumnName("mask");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.HasKey("Id")
                        .HasName("pk_bank_accounts");

                    b.HasAlternateKey("OrgId", "Id")
                        .HasName("ak_bank_accounts_org_id_id");

                    b.HasIndex("OrgId", "Name")
                        .HasDatabaseName("ix_bank_accounts_org_id_name");

                    b.ToTable("bank_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_bank_accounts_purpose", "purpose IN ('trust','deposit','operating')");
                        });
                });

            modelBuilder.Entity("LeaseBook.Modules.Directory.Domain.LeaseLite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DepositRequired")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("deposit_required")
                        .HasDefaultValueSql("0");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<decimal?>("LateFeeAmountOverride")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("late_fee_amount_override");

                    b.Property<int?>("LateFeeGraceDaysOverride")
                        .HasColumnType("integer")
                        .HasColumnName("late_fee_grace_days_override");

                    b.Property<string>("LateFeeKindOverride")
                        .HasColumnType("text")
                        .HasColumnName("late_fee_kind_override");

                    b.Property<int?>("LateFeeRateBpsOverride")
                        .HasColumnType("integer")
                        .HasColumnName("late_fee_rate_bps_override");

                    b.Property<int?>("LateFeeRentDueDayOverride")
                        .HasColumnType("integer")
                        .HasColumnName("late_fee_rent_due_day_override");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<decimal>("Rent")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("rent");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_lease_lite");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_lease_lite_tenant_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_lease_lite_unit_id");

                    b.HasIndex("OrgId", "TenantId")
                        .HasDatabaseName("ix_lease_lite_org_id_tenant_id");

                    b.HasIndex("OrgId", "UnitId")
                        .HasDatabaseName("ix_lease_lite_org_id_unit_id");

                    b.ToTable("lease_lite", null, t =>
                        {
                            t.HasCheckConstraint("ck_lease_lite_status", "status IN ('active','ended','pending')");
                        });
                });

            modelBuilder.Entity("LeaseBook.Modules.Directory.Domain.OrgSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountingBasis")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("cash")
                        .HasColumnName("accounting_basis");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("LateFeeAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(14,2)")
                        .HasDefaultValue(50m)
                        .HasColumnName("late_fee_amount");

                    b.Property<int>("LateFeeGraceDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("late_fee_grace_days");

                    b.Property<string>("LateFeeKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("flat")
                        .HasColumnName("late_fee_kind");

                    b.Property<int>("LateFeeRateBps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(500)
                        .HasColumnName("late_fee_rate_bps");

                    b.Property<string>("LegalName")
                        .HasColumnType("text")
                        .HasColumnName("legal_name");

                    b.Property<string>("LogoBlobRef")
                        .HasColumnType("text")
                        .HasColumnName("logo_blob_ref");

                    b.Property<string>("MoneyNegativeDisplay")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("minus")
                        .HasColumnName("money_negative_display");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("RentDueDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("rent_due_day");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Zip")
                        .HasColumnType("text")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_org_settings");

                    b.HasIndex("OrgId")
                        .IsUnique()
                        .HasDatabaseName("ix_org_settings_org_id");

                    b.ToTable("org_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_org_settings_accounting_basis", "accounting_basis IN ('cash','accrual')");

                            t.HasCheckConstraint("ck_org_settings_money_negative_display", "money_negative_display IN ('minus','parens')");
                        });
                });

            modelBuilder.Entity("LeaseBook.Modules.Directory.Domain.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DefaultMgmtFeeBps")
                        .HasColumnType("integer")
                        .HasColumnName("default_mgmt_fee_bps");

                    b.Property<string>("Initials")
                        .HasColumnType("text")
                        .HasColumnName("initials");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<decimal>("ReserveAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("reserve_amount")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id")
                        .HasName("pk_owners");

                    b.HasAlternateKey("OrgId", "Id")
                        .HasName("ak_owners_org_id_id");

                    b.HasIndex("OrgId", "Name")
                        .HasDatabaseName("ix_owners_org_id_name");

                    b.ToTable("owners", (string)null);
                });

            modelBuilder.Entity("LeaseBook.Modules.Directory.Domain.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<int?>("MgmtFeeBps")
                        .HasColumnType("integer")
                        .HasColumnName("mgmt_fee_bps");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Zip")
                        .HasColumnType("text")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_properties");

                    b.HasAlternateKey("OrgId", "Id")
                        .HasName("ak_properties_org_id_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_properties_owner_id");

                    b.HasIndex("OrgId", "Address")
                        .HasDatabaseName("ix_properties_org_id_address");

                    b.HasIndex("OrgId", "OwnerId")
                        .HasDatabaseName("ix_properties_org_id_owner_id");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("LeaseBook.Modules.Directory.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasAlternateKey("OrgId", "Id")
                        .HasName("ak_tenants_org_id_id");

                    b.HasIndex("OrgId", "DisplayName")
                        .HasDatabaseName("ix_tenants_org_id_display_name");

                    b.ToTable("tenants", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenants_status", "status IN ('current','late','prepaid','evicting','past')");
                        });
                });

            modelBuilder.Entity("LeaseBook.Modules.Directory.Domain.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<decimal>("Rent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("rent")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasAlternateKey("OrgId", "Id")
                        .HasName("ak_units_org_id_id");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_units_property_id");

                    b.HasIndex("OrgId", "PropertyId")
                        .HasDatabaseName("ix_units_org_id_property_id");

                    b.ToTable("units", null, t =>
                        {
                            t.HasCheckConstraint("ck_units_status", "status IN ('occupied','vacant','unavailable')");
                        });
                });

            modelBuilder.Entity("LeaseBook.Modules.Operations.Domain.BulkRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<int>("PeriodMonth")
                        .HasColumnType("integer")
                        .HasColumnName("period_month");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("integer")
                        .HasColumnName("period_year");

                    b.Property<string>("RunType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("run_type");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("summary_json");

                    b.HasKey("Id")
                        .HasName("pk_bulk_runs");

                    b.HasIndex("OrgId", "RunType", "PeriodYear", "PeriodMonth")
                        .HasDatabaseName("ix_bulk_runs_org_id_run_type_period_year_period_month");

                    b.ToTable("bulk_runs", (string)null);
                });

            modelBuilder.Entity("LeaseBook.Modules.Operations.Domain.BulkRunItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid?>("ResultingJournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("resulting_journal_entry_id");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_kind");

                    b.HasKey("Id")
                        .HasName("pk_bulk_run_items");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_bulk_run_items_run_id");

                    b.HasIndex("OrgId", "RunId")
                        .HasDatabaseName("ix_bulk_run_items_org_id_run_id");

                    b.ToTable("bulk_run_items", (string)null);
                });

            modelBuilder.Entity("LeaseBook.Modules.Reporting.Delivery.StatementDeliveryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtifactKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artifact_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("PeriodMonth")
                        .HasColumnType("integer")
                        .HasColumnName("period_month");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("integer")
                        .HasColumnName("period_year");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_email");

                    b.HasKey("Id")
                        .HasName("pk_statement_deliveries");

                    b.HasIndex("OrgId", "OwnerId", "PeriodYear", "PeriodMonth")
                        .HasDatabaseName("ix_statement_deliveries_org_id_owner_id_period_year_period_mon");

                    b.ToTable("statement_deliveries", null, t =>
                        {
                            t.HasCheckConstraint("ck_statement_deliveries_state", "state IN ('queued', 'sent', 'failed')");
                        });
                });

            modelBuilder.Entity("LeaseBook.Web.Auth.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("LeaseBook.Web.Onboarding.Persistence.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("Actor")
                        .HasColumnType("uuid")
                        .HasColumnName("actor");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_kind");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<string>("MappingProfile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mapping_profile");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<string>("SourceFilename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_filename");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_batch_id");

                    b.HasKey("Id")
                        .HasName("pk_import_batches");

                    b.HasIndex("SupersedesBatchId")
                        .HasDatabaseName("ix_import_batches_supersedes_batch_id");

                    b.HasIndex("OrgId", "SupersedesBatchId")
                        .HasDatabaseName("ix_import_batches_org_id_supersedes_batch_id");

                    b.HasIndex("OrgId", "EntityKind", "Status")
                        .HasDatabaseName("ix_import_batches_org_id_entity_kind_status");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("LeaseBook.Web.Onboarding.Persistence.ImportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("errors_json");

                    b.Property<string>("MappedJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("mapped_json");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<Guid?>("ResultingJournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("resulting_journal_entry_id");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<string>("RowStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("row_status");

                    b.HasKey("Id")
                        .HasName("pk_import_rows");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_import_rows_batch_id");

                    b.HasIndex("OrgId", "BatchId")
                        .HasDatabaseName("ix_import_rows_org_id_batch_id");

                    b.ToTable("import_rows", (string)null);
                });

            modelBuilder.Entity("LeaseBook.Web.Onboarding.Persistence.MigrationVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("actual_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("CutoverDate")
                        .HasColumnType("date")
                        .HasColumnName("cutover_date");

                    b.Property<string>("ExpectedJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("expected_json");

                    b.Property<bool>("IsTied")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tied");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("ReportSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("report_snapshot");

                    b.Property<DateTime?>("SignedOffAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_off_at");

                    b.Property<string>("SignedOffBy")
                        .HasColumnType("text")
                        .HasColumnName("signed_off_by");

                    b.Property<decimal>("VarianceTotal")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("variance_total");

                    b.HasKey("Id")
                        .HasName("pk_migration_verifications");

                    b.HasIndex("OrgId", "CutoverDate")
                        .HasDatabaseName("ix_migration_verifications_org_id_cutover_date");

                    b.ToTable("migration_verifications", (string)null);
                });

            modelBuilder.Entity("LeaseBook.Web.Persistence.Org", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_orgs");

                    b.ToTable("orgs", (string)null);
                });

            modelBuilder.Entity("LeaseBook.Web.Tenancy.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("After")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<string>("Before")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("OrgId", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_org_id_occurred_at");

                    b.HasIndex("OrgId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_events_org_id_entity_type_entity_id");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("LeaseBook.Modules.Accounting.Domain.BankLineState", b =>
                {
                    b.HasOne("LeaseBook.Modules.Accounting.Domain.JournalLine", null)
                        .WithMany()
                        .HasForeignKey("JournalLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bank_line_status_journal_line_journal_line_id");

                    b.HasOne("LeaseBook.Modules.Accounting.Domain.BankReconciliation", null)
                        .WithMany()
                        .HasForeignKey("ReconciliationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bank_line_status_bank_reconciliation_reconciliation_id");
                });

            modelBuilder.Entity("LeaseBook.Modules.Accounting.Domain.JournalEntry", b =>
                {
                    b.HasOne("LeaseBook.Modules.Accounting.Domain.JournalEntry", null)
                        .WithMany()
                        .HasForeignKey("ReversesEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_journal_entries_journal_entries_reverses_entry_id");
                });

            modelBuilder.Entity("LeaseBook.Modules.Accounting.Domain.JournalLine", b =>
                {
                    b.HasOne("LeaseBook.Modules.Accounting.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_lines_accounts_account_id");

                    b.HasOne("LeaseBook.Modules.Accounting.Domain.JournalEntry", null)
                        .WithMany("Lines")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journal_lines_journal_entries_entry_id");
                });

            modelBuilder.Entity("LeaseBook.Modules.Banking.Domain.StatementLine", b =>
                {
                    b.HasOne("LeaseBook.Modules.Banking.Domain.StatementImport", null)
                        .WithMany()
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_statement_lines_statement_imports_import_id");
                });

            modelBuilder.Entity("LeaseBook.Modules.Banking.Domain.StatementMatch", b =>
                {
                    b.HasOne("LeaseBook.Modules.Banking.Domain.StatementLine", null)
                        .WithMany()
                        .HasForeignKey("StatementLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_statement_matches_statement_lines_statement_line_id");
                });

            modelBuilder.Entity("LeaseBook.Modules.Directory.Domain.LeaseLite", b =>
                {
                    b.HasOne("LeaseBook.Modules.Directory.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lease_lite_tenant_tenant_id");

                    b.HasOne("LeaseBook.Modules.Directory.Domain.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lease_lite_unit_unit_id");
                });

            modelBuilder.Entity("LeaseBook.Modules.Directory.Domain.Property", b =>
                {
                    b.HasOne("LeaseBook.Modules.Directory.Domain.Owner", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_properties_owners_owner_id");
                });

            modelBuilder.Entity("LeaseBook.Modules.Directory.Domain.Unit", b =>
                {
                    b.HasOne("LeaseBook.Modules.Directory.Domain.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_units_properties_property_id");
                });

            modelBuilder.Entity("LeaseBook.Modules.Operations.Domain.BulkRunItem", b =>
                {
                    b.HasOne("LeaseBook.Modules.Operations.Domain.BulkRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bulk_run_items_bulk_runs_run_id");
                });

            modelBuilder.Entity("LeaseBook.Web.Onboarding.Persistence.ImportBatch", b =>
                {
                    b.HasOne("LeaseBook.Web.Onboarding.Persistence.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("SupersedesBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_import_batches_import_batches_supersedes_batch_id");
                });

            modelBuilder.Entity("LeaseBook.Web.Onboarding.Persistence.ImportRow", b =>
                {
                    b.HasOne("LeaseBook.Web.Onboarding.Persistence.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_import_rows_import_batches_batch_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("LeaseBook.Web.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("LeaseBook.Web.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("LeaseBook.Web.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("LeaseBook.Web.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("LeaseBook.Modules.Accounting.Domain.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
